package com.guido.app

object Constants {
    const val GCP_API_KEY = "AIzaSyBLXHjQ9_gyeSoRfndyiAz0lfvm-3fgpxY"

    data class PlaceType(val id: String, val displayName: String, var isSelected : Boolean = false)

    val placeTypes = listOf(
        PlaceType("accounting", "Accounting"),
        PlaceType("airport", "Airport"),
        PlaceType("amusement_park", "Amusement Park"),
        PlaceType("aquarium", "Aquarium"),
        PlaceType("art_gallery", "Art Gallery"),
        PlaceType("atm", "ATM"),
        PlaceType("bakery", "Bakery"),
        PlaceType("bank", "Bank"),
        PlaceType("bar", "Bar"),
        PlaceType("beauty_salon", "Beauty Salon"),
        PlaceType("bicycle_store", "Bicycle Store"),
        PlaceType("book_store", "Book Store"),
        PlaceType("bowling_alley", "Bowling Alley"),
        PlaceType("bus_station", "Bus Station"),
        PlaceType("cafe", "Cafe"),
        PlaceType("campground", "Campground"),
        PlaceType("car_dealer", "Car Dealer"),
        PlaceType("car_rental", "Car Rental"),
        PlaceType("car_repair", "Car Repair"),
        PlaceType("car_wash", "Car Wash"),
        PlaceType("casino", "Casino"),
        PlaceType("cemetery", "Cemetery"),
        PlaceType("church", "Church"),
        PlaceType("city_hall", "City Hall"),
        PlaceType("clothing_store", "Clothing Store"),
        PlaceType("convenience_store", "Convenience Store"),
        PlaceType("courthouse", "Courthouse"),
        PlaceType("dentist", "Dentist"),
        PlaceType("department_store", "Department Store"),
        PlaceType("doctor", "Doctor"),
        PlaceType("drugstore", "Drugstore"),
        PlaceType("electrician", "Electrician"),
        PlaceType("electronics_store", "Electronics Store"),
        PlaceType("embassy", "Embassy"),
        PlaceType("fire_station", "Fire Station"),
        PlaceType("florist", "Florist"),
        PlaceType("funeral_home", "Funeral Home"),
        PlaceType("furniture_store", "Furniture Store"),
        PlaceType("gas_station", "Gas Station"),
        PlaceType("gym", "Gym"),
        PlaceType("hair_care", "Hair Care"),
        PlaceType("hardware_store", "Hardware Store"),
        PlaceType("hindu_temple", "Hindu Temple"),
        PlaceType("home_goods_store", "Home Goods Store"),
        PlaceType("hospital", "Hospital"),
        PlaceType("insurance_agency", "Insurance Agency"),
        PlaceType("jewelry_store", "Jewelry Store"),
        PlaceType("laundry", "Laundry"),
        PlaceType("lawyer", "Lawyer"),
        PlaceType("library", "Library"),
        PlaceType("light_rail_station", "Light Rail Station"),
        PlaceType("liquor_store", "Liquor Store"),
        PlaceType("local_government_office", "Local Government Office"),
        PlaceType("locksmith", "Locksmith"),
        PlaceType("lodging", "Lodging"),
        PlaceType("meal_delivery", "Meal Delivery"),
        PlaceType("meal_takeaway", "Meal Takeaway"),
        PlaceType("mosque", "Mosque"),
        PlaceType("movie_rental", "Movie Rental"),
        PlaceType("movie_theater", "Movie Theater"),
        PlaceType("moving_company", "Moving Company"),
        PlaceType("museum", "Museum"),
        PlaceType("night_club", "Night Club"),
        PlaceType("painter", "Painter"),
        PlaceType("park", "Park"),
        PlaceType("parking", "Parking"),
        PlaceType("pet_store", "Pet Store"),
        PlaceType("pharmacy", "Pharmacy"),
        PlaceType("physiotherapist", "Physiotherapist"),
        PlaceType("plumber", "Plumber"),
        PlaceType("police", "Police"),
        PlaceType("post_office", "Post Office"),
        PlaceType("primary_school", "Primary School"),
        PlaceType("real_estate_agency", "Real Estate Agency"),
        PlaceType("restaurant", "Restaurant"),
        PlaceType("roofing_contractor", "Roofing Contractor"),
        PlaceType("rv_park", "RV Park"),
        PlaceType("school", "School"),
        PlaceType("secondary_school", "Secondary School"),
        PlaceType("shoe_store", "Shoe Store"),
        PlaceType("shopping_mall", "Shopping Mall"),
        PlaceType("spa", "Spa"),
        PlaceType("stadium", "Stadium"),
        PlaceType("storage", "Storage"),
        PlaceType("store", "Store"),
        PlaceType("subway_station", "Subway Station"),
        PlaceType("supermarket", "Supermarket"),
        PlaceType("synagogue", "Synagogue"),
        PlaceType("taxi_stand", "Taxi Stand"),
        PlaceType("tourist_attraction", "Tourist Attraction"),
        PlaceType("train_station", "Train Station"),
        PlaceType("transit_station", "Transit Station"),
        PlaceType("travel_agency", "Travel Agency"),
        PlaceType("university", "University"),
        PlaceType("veterinary_care", "Veterinary Care"),
        PlaceType("zoo", "Zoo")
    )


}
