package com.innoappsai.guido

object CurrencyConstant {

    val countryCurrencyList = listOf(
        "United States" to "$",
        "United Kingdom" to "£",
        "Eurozone" to "€",
        "Japan" to "¥",
        "Canada" to "C$",
        "Australia" to "A$",
        "Switzerland" to "Fr.",
        "India" to "₹",
        "Brazil" to "R$",
        "Russia" to "₽",
        "China" to "¥",
        "South Korea" to "₩",
        "Mexico" to "Mex$",
        "South Africa" to "R",
        "Saudi Arabia" to "﷼",
        "United Arab Emirates" to "د.إ",
        "Singapore" to "S$",
        "Germany" to "€",
        "France" to "€",
        "Italy" to "€",
        "Spain" to "€",
        "Netherlands" to "€",
        "Belgium" to "€",
        "Luxembourg" to "€",
        "Austria" to "€",
        "Ireland" to "€",
        "Portugal" to "€",
        "Greece" to "€",
        "Sweden" to "kr",
        "Norway" to "kr",
        "Denmark" to "kr",
        "Poland" to "zł",
        "Czech Republic" to "Kč",
        "Hungary" to "Ft",
        "Turkey" to "₺",
        "Egypt" to "E£",
        "Argentina" to "$",
        "Chile" to "$",
        "Colombia" to "$",
        "Peru" to "S/.",
        "Venezuela" to "Bs.",
        "Bolivia" to "Bs.",
        "Paraguay" to "₲",
        "Thailand" to "฿",
        "Malaysia" to "RM",
        "Indonesia" to "Rp",
        "Philippines" to "₱",
        "Vietnam" to "₫",
        "New Zealand" to "NZ$",
        "Fiji" to "FJ$",
        "Papua New Guinea" to "K",
        "Solomon Islands" to "SI$",
        "Samoa" to "WS$",
        "Tonga" to "T$",
        "Tonga" to "VT",
        "Cambodia" to "៛",
        "Myanmar" to "Ks",
        "Laos" to "₭",
        "Sri Lanka" to "₨",
        "Bangladesh" to "৳",
        "Pakistan" to "Rs",
        "Afghanistan" to "؋",
        "Iran" to "﷼",
        "Iraq" to "ع.د",
        "Israel" to "₪",
        "Jordan" to "د.ا",
        "Lebanon" to "ل.ل",
        "Syria" to "£S",
        "Kuwait" to "د.ك",
        "Qatar" to "ر.ق",
        "Oman" to "ر.ع.",
        "Yemen" to "﷼",
        "Ethiopia" to "Br",
        "Kenya" to "Ksh",
        "Nigeria" to "₦",
        "South Sudan" to "SSP",
        "Tanzania" to "Sh",
        "Uganda" to "USh",
        "Zimbabwe" to "Z$",
        "Zambia" to "ZK",
        "Namibia" to "N$",
        "Botswana" to "P",
        "Angola" to "Kz",
        "Mozambique" to "MT",
        "Madagascar" to "Ar",
        "Mauritius" to "₨",
        "Mauritania" to "UM",
        "Cameroon" to "FCFA",
        "Morocco" to "د.م.",
        "Tunisia" to "د.ت",
        "Libya" to "ل.د",
        "Sudan" to "ج.س",
        "Ghana" to "₵",
        "Ivory Coast" to "CFA",
        "Niger" to "CFA",
        "Mali" to "CFA",
        "Senegal" to "CFA",
        "Mauritania" to "Ouguiya",
        "Sierra Leone" to "Le",
        "Liberia" to "L$",
        "Guinea" to "FG",
        "Guinea-Bissau" to "CFA",
        "Equatorial Guinea" to "CFA",
        "Djibouti" to "Fdj",
        "Eritrea" to "Nfk",
        "Somalia" to "Sh.so",
        "Nepal" to "₨",
        "Bhutan" to "Nu.",
        "Bahrain" to "د.ب",
        "Maldives" to "Rf",
        "Seychelles" to "₨",
        "Falkland Islands" to "FK£",
        "Cook Islands" to "$",
        "Nauru" to "$",
        "Tuvalu" to "$",
        "Kiribati" to "$",
        "Marshall Islands" to "$",
        "Palau" to "$",
        "Micronesia" to "$",
        "Tajikistan" to "ЅМ",
        "Kyrgyzstan" to "сом",
        "Turkmenistan" to "T",
        "Uzbekistan" to "лв",
        "Kazakhstan" to "₸",
        "Armenia" to "֏",
        "Azerbaijan" to "₼",
        "Georgia" to "₾"
    )

    val countryCurrencyMap: Map<String, String> = countryCurrencyList.toMap()

}